#!/bin/sh

tempimage=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 32 | head -n 1)
image=$1; shift

# Variant can be used to alter tag names.
VARIANT="${VARIANT}"

# Build container
docker build -t ${tempimage} $@

# Extract tag versions
versions=$(docker inspect -f "{{.Config.Labels.version_tags}}" ${tempimage} | sed -r -e 's/"|\[|\]//g' -e 's/,/ /g')

# Create tags from the list
for version in $versions; do
  tag=${version}-${VARIANT}
  tag=${tag%-}

  docker tag ${tempimage} ${image}:${tag}
  echo "==> tagged: ${image}:${tag}"
done

# Tag latest (based on variant or latest)
latest=${VARIANT:-latest}
docker tag ${tempimage} ${image}:${latest}
echo "==> tagged: ${image}:${latest}"

docker rmi ${tempimage}
